Fix dev environment

diff --git a/.github/workflows/pull-upstream.yml b/.github/workflows/pull-upstream.yml
--- a/.github/workflows/pull-upstream.yml
+++ b/.github/workflows/pull-upstream.yml
@@ -17,7 +17,7 @@ jobs:
           fetch-depth: 0
       - name: clone upstream
         run: |
-          git clone -b release --single-branch https://github.com/mozilla/gecko-dev --depth 1 upstream_release
+          git clone -b master --single-branch https://github.com/mozilla/gecko-dev --depth 1 upstream_release
           rm -rf ./upstream_release/.git ./upstream_release/.github
       - name: copy upstream to this_repo
         run: |
@@ -26,13 +26,20 @@ jobs:
           cp -r ./nyanrus_release/.github temp_release
           cp ./nyanrus_release/.gitmodules temp_release
           cp -r ./nyanrus_release/noraneko temp_release
-      - name: apply git patches
+      - id: apply-git-patches
+        name: apply git patches
+        continue-on-error: true
         run: |
           cd temp_release
-          git apply --ignore-space-change --ignore-whitespace .github/patches/upstream/*.patch
+          git apply --ignore-space-change  --reject --ignore-whitespace .github/patches/upstream/*.patch
           cp -f .github/workflows/setup.ico other-licenses/7zstub/firefox/setup.ico
           cp -f .github/workflows/7zSD.ARM64.sfx other-licenses/7zstub/firefox/7zSD.ARM64.sfx
           cp -f .github/workflows/7zSD.Win32.sfx other-licenses/7zstub/firefox/7zSD.Win32.sfx
+      - name: detect patch error
+        if: ${{ steps.apply-git-patches.outcome == 'failure' }}
+        run: |
+          echo "Patch Error!"
+          exit 1
       - name: push
         run: |
           cd temp_release
